package Bill;

import jakarta.persistence.*;

import java.util.Objects;


@Entity
@Table(name = "Bill")
public class Bill {

    /**
     * The unique identifier for the bill record.
     * This value is automatically generated by the persistence provider.
     */
    @Id
    @GeneratedValue
    private long id;

    /**
     * The type of bill (e.g., electricity, water, etc.).
     * This field cannot be null in the database.
     */
    @Column(nullable = false)
    private String billType;

    /**
     * The price amount for the bill.
     * This field cannot be null in the database.
     */
    @Column(nullable = false)
    private double price;

    /**
     * Default constructor required by JPA.
     */
    public Bill() {
    }

    /**
     * Constructs a new Bill with the specified details.
     *
     * @param id the unique identifier for the bill
     * @param billType the type of bill
     * @param price the price amount for the bill
     */
    public Bill(long id, String billType, double price) {

        this.billType = billType;
        this.price = price;
    }

    /**
     * Gets the unique identifier of this bill.
     *
     * @return the bill's ID
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of this bill.
     *
     * @param id the new ID to set
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Gets the type of this bill.
     *
     * @return the bill type
     */
    public String getBillType() {
        return billType;
    }

    /**
     * Sets the type of this bill.
     *
     * @param billType the new bill type to set
     */
    public void setBillType(String billType) {
        this.billType = billType;
    }

    /**
     * Gets the price amount of this bill.
     *
     * @return the bill price
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets the price amount of this bill.
     *
     * @param price the new price to set
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * Compares this bill to another object for equality.
     * Two bills are considered equal if they have the same ID, bill type, and price.
     *
     * @param o the object to compare with
     * @return true if the objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Bill bill = (Bill) o;
        return id == bill.id && Double.compare(price, bill.price) == 0 && Objects.equals(billType, bill.billType);
    }

    /**
     * Generates a hash code for this bill based on its ID, type, and price.
     *
     * @return a hash code value for this object
     */
    @Override
    public int hashCode() {
        return Objects.hash(id, billType, price);
    }

    /**
     * Returns a string representation of this bill.
     * The string contains the bill's ID, type, and price.
     *
     * @return a string representation of the bill
     */
    @Override
    public String toString() {
        return "Bill{" +
                "id=" + id +
                ", billType='" + billType + '\'' +
                ", price=" + price +
                '}';
    }
}
